# Generated by Neurodocker and Reproenv.

FROM ubuntu:jammy

ARG DEBIAN_FRONTEND="noninteractive"

RUN apt-get update -qq \
           && apt-get install -y -qq --no-install-recommends \
                  git \
                  wget \
                  make \
                  gnupg2 \
           && rm -rf /var/lib/apt/lists/*

## Install python
RUN : \
    && . /etc/lsb-release \
    && apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys F23C5A6CF475977595C89F51BA6932366A755776 \
    && echo deb http://ppa.launchpad.net/deadsnakes/ppa/ubuntu $DISTRIB_CODENAME main > /etc/apt/sources.list.d/deadsnakes.list \
    && apt-get update -qq \
    && apt-get install -qq -y --no-install-recommends \
        python3.10 \
        python3-pip && \
    apt-get clean && \
    rm -rf \
        /tmp/hsperfdata* \
        /var/*/apt/*/partial \
        /var/lib/apt/lists/* \
        /var/log/apt/term* && \
    echo '\n' && \
    python3 --version && \
    pip3 list && \
    echo '\n'

RUN mkdir -p /home/neuro/bidsMReye/models
WORKDIR /home/neuro/bidsMReye

COPY [".", "/home/neuro/bidsMReye"]
RUN pip3 install .

RUN bidsmreye_model
RUN bidsmreye_model --model_name 1_guided_fixations && \
    bidsmreye_model --model_name 2_pursuit && \
    bidsmreye_model --model_name 3_openclosed && \
    bidsmreye_model --model_name 3_pursuit && \
    bidsmreye_model --model_name 4_pursuit && \
    bidsmreye_model --model_name 5_free_viewing && \
    bidsmreye_model --model_name 1to5

ENTRYPOINT [ "/neurodocker/startup.sh" ]
COPY ["./docker/entrypoint.sh", \
      "/neurodocker/startup.sh"]

RUN chmod +x /neurodocker/startup.sh
