;  See https://tox.wiki/en
[tox]
requires =
    tox>=4
    tox-uv
; run lint by default when just calling "tox"
env_list = lint

; ENVIRONMENTS
; ------------

[global_var]
passenv =
    CI
    USERNAME
    # Pass user color preferences through
    PY_COLORS
    FORCE_COLOR
    NO_COLOR
    CLICOLOR
    CLICOLOR_FORCE


; COMMANDS
; --------
[testenv:test]
description = run tests with coverage
passenv = {[global_var]passenv}
dependency_groups = test
commands =
    pytest --cov bidsmreye --cov-report=xml

[testenv:lint]
description = install pre-commit hooks and run all linters and formatters
skip_install = true
passenv = {[global_var]passenv}
deps = pre-commit
commands =
    pre-commit install
	pre-commit run --all-files --show-diff-on-failure {posargs:}
