---
name: Check Markdown links

# checking for any dead links in markdown files

on:
    push:
        branches:
        -   main
    pull_request:
        branches: ['*']

jobs:
    markdown-link-check:
        runs-on: ubuntu-latest
        steps:
        -   uses: actions/checkout@master
        -   uses: gaurav-nelson/github-action-markdown-link-check@v1
            with:
                use-quiet-mode: yes
                use-verbose-mode: yes
                config-file: mlc_config.json
